// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cashier_report.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCashierReport = `-- name: CreateCashierReport :one
INSERT INTO cashier_reports (
  store_id, cashier_id, cashier_name, start_time, end_time, total_transactions, total_revenue, total_profit
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, store_id, cashier_id, cashier_name, start_time, end_time, total_transactions, total_revenue, total_profit, created_at
`

type CreateCashierReportParams struct {
	StoreID           pgtype.UUID        `json:"store_id"`
	CashierID         pgtype.UUID        `json:"cashier_id"`
	CashierName       string             `json:"cashier_name"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	TotalTransactions int32              `json:"total_transactions"`
	TotalRevenue      int64              `json:"total_revenue"`
	TotalProfit       int64              `json:"total_profit"`
}

func (q *Queries) CreateCashierReport(ctx context.Context, arg CreateCashierReportParams) (CashierReport, error) {
	row := q.db.QueryRow(ctx, createCashierReport,
		arg.StoreID,
		arg.CashierID,
		arg.CashierName,
		arg.StartTime,
		arg.EndTime,
		arg.TotalTransactions,
		arg.TotalRevenue,
		arg.TotalProfit,
	)
	var i CashierReport
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CashierID,
		&i.CashierName,
		&i.StartTime,
		&i.EndTime,
		&i.TotalTransactions,
		&i.TotalRevenue,
		&i.TotalProfit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCashierReport = `-- name: DeleteCashierReport :exec
DELETE FROM cashier_reports
WHERE id = $1 AND store_id = $2
`

type DeleteCashierReportParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

func (q *Queries) DeleteCashierReport(ctx context.Context, arg DeleteCashierReportParams) error {
	_, err := q.db.Exec(ctx, deleteCashierReport, arg.ID, arg.StoreID)
	return err
}

const getCashierReportById = `-- name: GetCashierReportById :one
SELECT id, store_id, cashier_id, cashier_name, start_time, end_time, total_transactions, total_revenue, total_profit, created_at FROM cashier_reports
WHERE id = $1 AND store_id = $2
`

type GetCashierReportByIdParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

func (q *Queries) GetCashierReportById(ctx context.Context, arg GetCashierReportByIdParams) (CashierReport, error) {
	row := q.db.QueryRow(ctx, getCashierReportById, arg.ID, arg.StoreID)
	var i CashierReport
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CashierID,
		&i.CashierName,
		&i.StartTime,
		&i.EndTime,
		&i.TotalTransactions,
		&i.TotalRevenue,
		&i.TotalProfit,
		&i.CreatedAt,
	)
	return i, err
}

const getCashierReportsByCashier = `-- name: GetCashierReportsByCashier :many
SELECT id, store_id, cashier_id, cashier_name, start_time, end_time, total_transactions, total_revenue, total_profit, created_at FROM cashier_reports
WHERE store_id = $1 AND cashier_id = $2
ORDER BY created_at DESC
`

type GetCashierReportsByCashierParams struct {
	StoreID   pgtype.UUID `json:"store_id"`
	CashierID pgtype.UUID `json:"cashier_id"`
}

func (q *Queries) GetCashierReportsByCashier(ctx context.Context, arg GetCashierReportsByCashierParams) ([]CashierReport, error) {
	rows, err := q.db.Query(ctx, getCashierReportsByCashier, arg.StoreID, arg.CashierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashierReport
	for rows.Next() {
		var i CashierReport
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CashierID,
			&i.CashierName,
			&i.StartTime,
			&i.EndTime,
			&i.TotalTransactions,
			&i.TotalRevenue,
			&i.TotalProfit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCashierReportsByStore = `-- name: GetCashierReportsByStore :many
SELECT id, store_id, cashier_id, cashier_name, start_time, end_time, total_transactions, total_revenue, total_profit, created_at FROM cashier_reports
WHERE store_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCashierReportsByStore(ctx context.Context, storeID pgtype.UUID) ([]CashierReport, error) {
	rows, err := q.db.Query(ctx, getCashierReportsByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashierReport
	for rows.Next() {
		var i CashierReport
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CashierID,
			&i.CashierName,
			&i.StartTime,
			&i.EndTime,
			&i.TotalTransactions,
			&i.TotalRevenue,
			&i.TotalProfit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unmarkTransactionsAsReported = `-- name: UnmarkTransactionsAsReported :exec
UPDATE transactions
SET is_reported = false
WHERE store_id = $1 AND cashier_id = $2 AND transaction_time >= $3 AND transaction_time <= $4
`

type UnmarkTransactionsAsReportedParams struct {
	StoreID           pgtype.UUID      `json:"store_id"`
	CashierID         pgtype.UUID      `json:"cashier_id"`
	TransactionTime   pgtype.Timestamp `json:"transaction_time"`
	TransactionTime_2 pgtype.Timestamp `json:"transaction_time_2"`
}

func (q *Queries) UnmarkTransactionsAsReported(ctx context.Context, arg UnmarkTransactionsAsReportedParams) error {
	_, err := q.db.Exec(ctx, unmarkTransactionsAsReported,
		arg.StoreID,
		arg.CashierID,
		arg.TransactionTime,
		arg.TransactionTime_2,
	)
	return err
}
