// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: master_product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMasterProduct = `-- name: CreateMasterProduct :one
INSERT INTO master_products (
  barcode, name, photo_url, photo_path, category_id, brand_id, unit, source, is_generated_barcode, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, barcode, name, photo_url, photo_path, category_id, brand_id, unit, source, is_generated_barcode, is_active, created_by, created_at, updated_at
`

type CreateMasterProductParams struct {
	Barcode            string      `json:"barcode"`
	Name               string      `json:"name"`
	PhotoUrl           pgtype.Text `json:"photo_url"`
	PhotoPath          pgtype.Text `json:"photo_path"`
	CategoryID         pgtype.UUID `json:"category_id"`
	BrandID            pgtype.UUID `json:"brand_id"`
	Unit               pgtype.Text `json:"unit"`
	Source             pgtype.Text `json:"source"`
	IsGeneratedBarcode pgtype.Bool `json:"is_generated_barcode"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateMasterProduct(ctx context.Context, arg CreateMasterProductParams) (MasterProduct, error) {
	row := q.db.QueryRow(ctx, createMasterProduct,
		arg.Barcode,
		arg.Name,
		arg.PhotoUrl,
		arg.PhotoPath,
		arg.CategoryID,
		arg.BrandID,
		arg.Unit,
		arg.Source,
		arg.IsGeneratedBarcode,
		arg.CreatedBy,
	)
	var i MasterProduct
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.Name,
		&i.PhotoUrl,
		&i.PhotoPath,
		&i.CategoryID,
		&i.BrandID,
		&i.Unit,
		&i.Source,
		&i.IsGeneratedBarcode,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMasterProduct = `-- name: GetMasterProduct :one
SELECT id, barcode, name, photo_url, photo_path, category_id, brand_id, unit, source, is_generated_barcode, is_active, created_by, created_at, updated_at FROM master_products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMasterProduct(ctx context.Context, id pgtype.UUID) (MasterProduct, error) {
	row := q.db.QueryRow(ctx, getMasterProduct, id)
	var i MasterProduct
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.Name,
		&i.PhotoUrl,
		&i.PhotoPath,
		&i.CategoryID,
		&i.BrandID,
		&i.Unit,
		&i.Source,
		&i.IsGeneratedBarcode,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMasterProducts = `-- name: ListMasterProducts :many
SELECT id, barcode, name, photo_url, photo_path, category_id, brand_id, unit, source, is_generated_barcode, is_active, created_by, created_at, updated_at FROM master_products
ORDER BY id
`

func (q *Queries) ListMasterProducts(ctx context.Context) ([]MasterProduct, error) {
	rows, err := q.db.Query(ctx, listMasterProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterProduct
	for rows.Next() {
		var i MasterProduct
		if err := rows.Scan(
			&i.ID,
			&i.Barcode,
			&i.Name,
			&i.PhotoUrl,
			&i.PhotoPath,
			&i.CategoryID,
			&i.BrandID,
			&i.Unit,
			&i.Source,
			&i.IsGeneratedBarcode,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
