// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	IsActive  pgtype.Bool      `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type CashierReport struct {
	ID                pgtype.UUID        `json:"id"`
	StoreID           pgtype.UUID        `json:"store_id"`
	CashierID         pgtype.UUID        `json:"cashier_id"`
	CashierName       string             `json:"cashier_name"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	TotalTransactions int32              `json:"total_transactions"`
	TotalRevenue      int64              `json:"total_revenue"`
	TotalProfit       int64              `json:"total_profit"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	IsActive  pgtype.Bool      `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type MasterProduct struct {
	ID                 pgtype.UUID      `json:"id"`
	Barcode            string           `json:"barcode"`
	Name               string           `json:"name"`
	PhotoUrl           pgtype.Text      `json:"photo_url"`
	PhotoPath          pgtype.Text      `json:"photo_path"`
	CategoryID         pgtype.UUID      `json:"category_id"`
	BrandID            pgtype.UUID      `json:"brand_id"`
	Unit               pgtype.Text      `json:"unit"`
	Source             pgtype.Text      `json:"source"`
	IsGeneratedBarcode pgtype.Bool      `json:"is_generated_barcode"`
	IsActive           pgtype.Bool      `json:"is_active"`
	CreatedBy          pgtype.UUID      `json:"created_by"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type PendingProduct struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	BuyPrice    int64              `json:"buy_price"`
	SellPrice   int64              `json:"sell_price"`
	Stock       int32              `json:"stock"`
	Category    string             `json:"category"`
	Description pgtype.Text        `json:"description"`
	Barcode     pgtype.Text        `json:"barcode"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StoreID     pgtype.UUID        `json:"store_id"`
}

type StockMovement struct {
	ID             pgtype.UUID      `json:"id"`
	StoreID        pgtype.UUID      `json:"store_id"`
	StoreProductID pgtype.UUID      `json:"store_product_id"`
	MovementType   string           `json:"movement_type"`
	Quantity       int32            `json:"quantity"`
	ReferenceType  pgtype.Text      `json:"reference_type"`
	ReferenceID    pgtype.UUID      `json:"reference_id"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Store struct {
	ID        pgtype.UUID      `json:"id"`
	OwnerID   pgtype.UUID      `json:"owner_id"`
	StoreCode string           `json:"store_code"`
	StoreName string           `json:"store_name"`
	Address   pgtype.Text      `json:"address"`
	Phone     pgtype.Text      `json:"phone"`
	IsActive  pgtype.Bool      `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	LogoUrl   pgtype.Text      `json:"logo_url"`
}

type StoreProduct struct {
	ID              pgtype.UUID      `json:"id"`
	StoreID         pgtype.UUID      `json:"store_id"`
	MasterProductID pgtype.UUID      `json:"master_product_id"`
	BuyPrice        int64            `json:"buy_price"`
	SellPrice       int64            `json:"sell_price"`
	Stock           int32            `json:"stock"`
	MinStock        int32            `json:"min_stock"`
	IsActive        pgtype.Bool      `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	LocalName       pgtype.Text      `json:"local_name"`
	LocalCategory   pgtype.Text      `json:"local_category"`
}

type Transaction struct {
	ID              pgtype.UUID      `json:"id"`
	StoreID         pgtype.UUID      `json:"store_id"`
	CashierID       pgtype.UUID      `json:"cashier_id"`
	InvoiceNumber   string           `json:"invoice_number"`
	TotalAmount     int64            `json:"total_amount"`
	PaidAmount      int64            `json:"paid_amount"`
	ChangeAmount    int64            `json:"change_amount"`
	PaymentMethod   string           `json:"payment_method"`
	TransactionTime pgtype.Timestamp `json:"transaction_time"`
	SyncStatus      string           `json:"sync_status"`
	DeviceID        pgtype.Text      `json:"device_id"`
	IsActive        pgtype.Bool      `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	IsReported      bool             `json:"is_reported"`
}

type TransactionItem struct {
	ID              pgtype.UUID      `json:"id"`
	TransactionID   pgtype.UUID      `json:"transaction_id"`
	StoreProductID  pgtype.UUID      `json:"store_product_id"`
	MasterProductID pgtype.UUID      `json:"master_product_id"`
	ProductName     string           `json:"product_name"`
	Barcode         string           `json:"barcode"`
	Quantity        int32            `json:"quantity"`
	BuyPrice        int64            `json:"buy_price"`
	SellPrice       int64            `json:"sell_price"`
	Subtotal        int64            `json:"subtotal"`
	IsActive        pgtype.Bool      `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	FullName     string           `json:"full_name"`
	Email        pgtype.Text      `json:"email"`
	Phone        pgtype.Text      `json:"phone"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	StoreID      pgtype.UUID      `json:"store_id"`
	IsActive     pgtype.Bool      `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	PhotoUrl     pgtype.Text      `json:"photo_url"`
}
