// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingProduct = `-- name: CreatePendingProduct :one
INSERT INTO pending_products (
  name, buy_price, sell_price, stock, category, description, barcode, image_url, store_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, buy_price, sell_price, stock, category, description, barcode, image_url, created_at, store_id
`

type CreatePendingProductParams struct {
	Name        string         `json:"name"`
	BuyPrice    pgtype.Numeric `json:"buy_price"`
	SellPrice   pgtype.Numeric `json:"sell_price"`
	Stock       int32          `json:"stock"`
	Category    string         `json:"category"`
	Description pgtype.Text    `json:"description"`
	Barcode     pgtype.Text    `json:"barcode"`
	ImageUrl    pgtype.Text    `json:"image_url"`
	StoreID     pgtype.UUID    `json:"store_id"`
}

func (q *Queries) CreatePendingProduct(ctx context.Context, arg CreatePendingProductParams) (PendingProduct, error) {
	row := q.db.QueryRow(ctx, createPendingProduct,
		arg.Name,
		arg.BuyPrice,
		arg.SellPrice,
		arg.Stock,
		arg.Category,
		arg.Description,
		arg.Barcode,
		arg.ImageUrl,
		arg.StoreID,
	)
	var i PendingProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BuyPrice,
		&i.SellPrice,
		&i.Stock,
		&i.Category,
		&i.Description,
		&i.Barcode,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.StoreID,
	)
	return i, err
}

const deletePendingProduct = `-- name: DeletePendingProduct :exec
DELETE FROM pending_products WHERE id = $1
`

func (q *Queries) DeletePendingProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingProduct, id)
	return err
}

const listPendingProducts = `-- name: ListPendingProducts :many
SELECT id, name, buy_price, sell_price, stock, category, description, barcode, image_url, created_at, store_id FROM pending_products ORDER BY created_at DESC
`

func (q *Queries) ListPendingProducts(ctx context.Context) ([]PendingProduct, error) {
	rows, err := q.db.Query(ctx, listPendingProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingProduct
	for rows.Next() {
		var i PendingProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BuyPrice,
			&i.SellPrice,
			&i.Stock,
			&i.Category,
			&i.Description,
			&i.Barcode,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
