// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountMasterProducts(ctx context.Context) (int64, error)
	CountPendingProducts(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateMasterProduct(ctx context.Context, arg CreateMasterProductParams) (MasterProduct, error)
	CreatePendingProduct(ctx context.Context, arg CreatePendingProductParams) (PendingProduct, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	CreateStoreProduct(ctx context.Context, arg CreateStoreProductParams) (StoreProduct, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) (TransactionItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePendingProduct(ctx context.Context, id pgtype.UUID) error
	DeleteStoreProduct(ctx context.Context, id pgtype.UUID) error
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetMasterProduct(ctx context.Context, id pgtype.UUID) (MasterProduct, error)
	GetPendingProduct(ctx context.Context, id pgtype.UUID) (PendingProduct, error)
	GetStore(ctx context.Context, id pgtype.UUID) (Store, error)
	GetStoreProduct(ctx context.Context, id pgtype.UUID) (StoreProduct, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	ListMasterProducts(ctx context.Context) ([]MasterProduct, error)
	ListPendingProducts(ctx context.Context) ([]PendingProduct, error)
	ListStoreProductsByStore(ctx context.Context, storeID pgtype.UUID) ([]StoreProduct, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdatePendingProduct(ctx context.Context, arg UpdatePendingProductParams) error
	UpdateStoreProduct(ctx context.Context, arg UpdateStoreProductParams) error
	UpdateStoreProductStock(ctx context.Context, arg UpdateStoreProductStockParams) error
}

var _ Querier = (*Queries)(nil)
