// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountMasterProducts(ctx context.Context) (int64, error)
	CountPendingProducts(ctx context.Context) (int64, error)
	CreateCashierReport(ctx context.Context, arg CreateCashierReportParams) (CashierReport, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateMasterProduct(ctx context.Context, arg CreateMasterProductParams) (MasterProduct, error)
	CreatePendingProduct(ctx context.Context, arg CreatePendingProductParams) (PendingProduct, error)
	CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	CreateStoreProduct(ctx context.Context, arg CreateStoreProductParams) (StoreProduct, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) (TransactionItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCashierReport(ctx context.Context, arg DeleteCashierReportParams) error
	DeleteMasterProduct(ctx context.Context, id pgtype.UUID) error
	DeletePendingProduct(ctx context.Context, id pgtype.UUID) error
	DeleteStockMovementsByMasterProduct(ctx context.Context, masterProductID pgtype.UUID) error
	DeleteStoreProduct(ctx context.Context, id pgtype.UUID) error
	DeleteStoreProductsByMasterID(ctx context.Context, masterProductID pgtype.UUID) error
	DeleteTransactionItemsByMasterProduct(ctx context.Context, masterProductID pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetAllStoreTransactions(ctx context.Context, storeID pgtype.UUID) ([]Transaction, error)
	GetAllStoreTransactionsByCashier(ctx context.Context, arg GetAllStoreTransactionsByCashierParams) ([]Transaction, error)
	GetCashierReportById(ctx context.Context, arg GetCashierReportByIdParams) (CashierReport, error)
	GetCashierReportsByCashier(ctx context.Context, arg GetCashierReportsByCashierParams) ([]CashierReport, error)
	GetCashierReportsByStore(ctx context.Context, storeID pgtype.UUID) ([]CashierReport, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetMasterProduct(ctx context.Context, id pgtype.UUID) (MasterProduct, error)
	GetPendingProduct(ctx context.Context, id pgtype.UUID) (PendingProduct, error)
	GetRecentStoreTransactions(ctx context.Context, storeID pgtype.UUID) ([]Transaction, error)
	GetRecentStoreTransactionsByCashier(ctx context.Context, arg GetRecentStoreTransactionsByCashierParams) ([]Transaction, error)
	GetStore(ctx context.Context, id pgtype.UUID) (Store, error)
	GetStoreDashboardStats(ctx context.Context, storeID pgtype.UUID) (GetStoreDashboardStatsRow, error)
	GetStoreDashboardStatsByCashier(ctx context.Context, arg GetStoreDashboardStatsByCashierParams) (GetStoreDashboardStatsByCashierRow, error)
	GetStoreProduct(ctx context.Context, id pgtype.UUID) (StoreProduct, error)
	GetTransactionItemsByTransactionId(ctx context.Context, transactionID pgtype.UUID) ([]TransactionItem, error)
	GetUnreportedTransactionsByCashier(ctx context.Context, arg GetUnreportedTransactionsByCashierParams) ([]Transaction, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	ListMasterProducts(ctx context.Context) ([]ListMasterProductsRow, error)
	ListPendingProducts(ctx context.Context) ([]PendingProduct, error)
	ListStoreProductsByStore(ctx context.Context, storeID pgtype.UUID) ([]ListStoreProductsByStoreRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersByStore(ctx context.Context, storeID pgtype.UUID) ([]User, error)
	MarkTransactionsAsReported(ctx context.Context, arg MarkTransactionsAsReportedParams) error
	UnmarkTransactionsAsReported(ctx context.Context, arg UnmarkTransactionsAsReportedParams) error
	UpdatePendingProduct(ctx context.Context, arg UpdatePendingProductParams) error
	UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error)
	UpdateStoreProduct(ctx context.Context, arg UpdateStoreProductParams) error
	UpdateStoreProductStock(ctx context.Context, arg UpdateStoreProductStockParams) error
	UpdateTransactionReportStatus(ctx context.Context, arg UpdateTransactionReportStatusParams) error
	UpdateUserFCMToken(ctx context.Context, arg UpdateUserFCMTokenParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserStoreID(ctx context.Context, arg UpdateUserStoreIDParams) error
}

var _ Querier = (*Queries)(nil)
