// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStore = `-- name: CreateStore :one
INSERT INTO stores (
  owner_id, store_code, store_name, address, phone
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, owner_id, store_code, store_name, address, phone, is_active, created_at, updated_at
`

type CreateStoreParams struct {
	OwnerID   pgtype.UUID `json:"owner_id"`
	StoreCode string      `json:"store_code"`
	StoreName string      `json:"store_name"`
	Address   pgtype.Text `json:"address"`
	Phone     pgtype.Text `json:"phone"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.OwnerID,
		arg.StoreCode,
		arg.StoreName,
		arg.Address,
		arg.Phone,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StoreCode,
		&i.StoreName,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStore = `-- name: GetStore :one
SELECT id, owner_id, store_code, store_name, address, phone, is_active, created_at, updated_at FROM stores
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStore(ctx context.Context, id pgtype.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStore, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StoreCode,
		&i.StoreName,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
