// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStoreProduct = `-- name: CreateStoreProduct :one
INSERT INTO store_products (
  store_id, master_product_id, buy_price, sell_price, stock, min_stock, local_name, local_category
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, store_id, master_product_id, buy_price, sell_price, stock, min_stock, is_active, created_at, updated_at, local_name, local_category
`

type CreateStoreProductParams struct {
	StoreID         pgtype.UUID    `json:"store_id"`
	MasterProductID pgtype.UUID    `json:"master_product_id"`
	BuyPrice        pgtype.Numeric `json:"buy_price"`
	SellPrice       pgtype.Numeric `json:"sell_price"`
	Stock           int32          `json:"stock"`
	MinStock        int32          `json:"min_stock"`
	LocalName       pgtype.Text    `json:"local_name"`
	LocalCategory   pgtype.Text    `json:"local_category"`
}

func (q *Queries) CreateStoreProduct(ctx context.Context, arg CreateStoreProductParams) (StoreProduct, error) {
	row := q.db.QueryRow(ctx, createStoreProduct,
		arg.StoreID,
		arg.MasterProductID,
		arg.BuyPrice,
		arg.SellPrice,
		arg.Stock,
		arg.MinStock,
		arg.LocalName,
		arg.LocalCategory,
	)
	var i StoreProduct
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.MasterProductID,
		&i.BuyPrice,
		&i.SellPrice,
		&i.Stock,
		&i.MinStock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocalName,
		&i.LocalCategory,
	)
	return i, err
}

const deleteStockMovementsByMasterProduct = `-- name: DeleteStockMovementsByMasterProduct :exec
DELETE FROM stock_movements WHERE store_product_id IN (SELECT id FROM store_products WHERE master_product_id = $1)
`

func (q *Queries) DeleteStockMovementsByMasterProduct(ctx context.Context, masterProductID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStockMovementsByMasterProduct, masterProductID)
	return err
}

const deleteStoreProduct = `-- name: DeleteStoreProduct :exec
DELETE FROM store_products WHERE id = $1
`

func (q *Queries) DeleteStoreProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStoreProduct, id)
	return err
}

const deleteStoreProductsByMasterID = `-- name: DeleteStoreProductsByMasterID :exec
DELETE FROM store_products WHERE master_product_id = $1
`

func (q *Queries) DeleteStoreProductsByMasterID(ctx context.Context, masterProductID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStoreProductsByMasterID, masterProductID)
	return err
}

const getStoreProduct = `-- name: GetStoreProduct :one
SELECT id, store_id, master_product_id, buy_price, sell_price, stock, min_stock, is_active, created_at, updated_at, local_name, local_category FROM store_products WHERE id = $1
`

func (q *Queries) GetStoreProduct(ctx context.Context, id pgtype.UUID) (StoreProduct, error) {
	row := q.db.QueryRow(ctx, getStoreProduct, id)
	var i StoreProduct
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.MasterProductID,
		&i.BuyPrice,
		&i.SellPrice,
		&i.Stock,
		&i.MinStock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocalName,
		&i.LocalCategory,
	)
	return i, err
}

const listStoreProductsByStore = `-- name: ListStoreProductsByStore :many
SELECT id, store_id, master_product_id, buy_price, sell_price, stock, min_stock, is_active, created_at, updated_at, local_name, local_category FROM store_products WHERE store_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStoreProductsByStore(ctx context.Context, storeID pgtype.UUID) ([]StoreProduct, error) {
	rows, err := q.db.Query(ctx, listStoreProductsByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreProduct
	for rows.Next() {
		var i StoreProduct
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.MasterProductID,
			&i.BuyPrice,
			&i.SellPrice,
			&i.Stock,
			&i.MinStock,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocalName,
			&i.LocalCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoreProduct = `-- name: UpdateStoreProduct :exec
UPDATE store_products
SET buy_price = $2, sell_price = $3, stock = $4, local_name = $5, local_category = $6
WHERE id = $1
`

type UpdateStoreProductParams struct {
	ID            pgtype.UUID    `json:"id"`
	BuyPrice      pgtype.Numeric `json:"buy_price"`
	SellPrice     pgtype.Numeric `json:"sell_price"`
	Stock         int32          `json:"stock"`
	LocalName     pgtype.Text    `json:"local_name"`
	LocalCategory pgtype.Text    `json:"local_category"`
}

func (q *Queries) UpdateStoreProduct(ctx context.Context, arg UpdateStoreProductParams) error {
	_, err := q.db.Exec(ctx, updateStoreProduct,
		arg.ID,
		arg.BuyPrice,
		arg.SellPrice,
		arg.Stock,
		arg.LocalName,
		arg.LocalCategory,
	)
	return err
}

const updateStoreProductStock = `-- name: UpdateStoreProductStock :exec
UPDATE store_products SET stock = stock + $2 WHERE id = $1
`

type UpdateStoreProductStockParams struct {
	ID    pgtype.UUID `json:"id"`
	Stock int32       `json:"stock"`
}

func (q *Queries) UpdateStoreProductStock(ctx context.Context, arg UpdateStoreProductStockParams) error {
	_, err := q.db.Exec(ctx, updateStoreProductStock, arg.ID, arg.Stock)
	return err
}
