// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscriptionPlan = `-- name: CreateSubscriptionPlan :one
INSERT INTO subscription_plans (name, duration_days, price, description, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, duration_days, price, description, is_active, created_at, updated_at
`

type CreateSubscriptionPlanParams struct {
	Name         string `json:"name"`
	DurationDays int32  `json:"duration_days"`
	Price        int64  `json:"price"`
	Description  string `json:"description"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) CreateSubscriptionPlan(ctx context.Context, arg CreateSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, createSubscriptionPlan,
		arg.Name,
		arg.DurationDays,
		arg.Price,
		arg.Description,
		arg.IsActive,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationDays,
		&i.Price,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscriptionTransaction = `-- name: CreateSubscriptionTransaction :one
INSERT INTO subscription_transactions (
    reference, merchant_ref, store_id, plan_id, amount, payment_method, payment_name, status, pay_code, qr_url, checkout_url, instructions_json, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, reference, merchant_ref, store_id, plan_id, amount, payment_method, payment_name, status, pay_code, qr_url, checkout_url, instructions_json, expires_at, paid_at, created_at, updated_at
`

type CreateSubscriptionTransactionParams struct {
	Reference        string             `json:"reference"`
	MerchantRef      string             `json:"merchant_ref"`
	StoreID          pgtype.UUID        `json:"store_id"`
	PlanID           int32              `json:"plan_id"`
	Amount           int64              `json:"amount"`
	PaymentMethod    string             `json:"payment_method"`
	PaymentName      string             `json:"payment_name"`
	Status           string             `json:"status"`
	PayCode          string             `json:"pay_code"`
	QrUrl            string             `json:"qr_url"`
	CheckoutUrl      string             `json:"checkout_url"`
	InstructionsJson string             `json:"instructions_json"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSubscriptionTransaction(ctx context.Context, arg CreateSubscriptionTransactionParams) (SubscriptionTransaction, error) {
	row := q.db.QueryRow(ctx, createSubscriptionTransaction,
		arg.Reference,
		arg.MerchantRef,
		arg.StoreID,
		arg.PlanID,
		arg.Amount,
		arg.PaymentMethod,
		arg.PaymentName,
		arg.Status,
		arg.PayCode,
		arg.QrUrl,
		arg.CheckoutUrl,
		arg.InstructionsJson,
		arg.ExpiresAt,
	)
	var i SubscriptionTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.MerchantRef,
		&i.StoreID,
		&i.PlanID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentName,
		&i.Status,
		&i.PayCode,
		&i.QrUrl,
		&i.CheckoutUrl,
		&i.InstructionsJson,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscriptionPlan = `-- name: DeleteSubscriptionPlan :exec
DELETE FROM subscription_plans WHERE id = $1
`

func (q *Queries) DeleteSubscriptionPlan(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSubscriptionPlan, id)
	return err
}

const getStoreProStatus = `-- name: GetStoreProStatus :one
SELECT id, store_name, pro_expires_at FROM stores WHERE id = $1
`

type GetStoreProStatusRow struct {
	ID           pgtype.UUID        `json:"id"`
	StoreName    string             `json:"store_name"`
	ProExpiresAt pgtype.Timestamptz `json:"pro_expires_at"`
}

func (q *Queries) GetStoreProStatus(ctx context.Context, id pgtype.UUID) (GetStoreProStatusRow, error) {
	row := q.db.QueryRow(ctx, getStoreProStatus, id)
	var i GetStoreProStatusRow
	err := row.Scan(&i.ID, &i.StoreName, &i.ProExpiresAt)
	return i, err
}

const getSubscriptionPlanByID = `-- name: GetSubscriptionPlanByID :one
SELECT id, name, duration_days, price, description, is_active, created_at, updated_at FROM subscription_plans WHERE id = $1
`

func (q *Queries) GetSubscriptionPlanByID(ctx context.Context, id int32) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPlanByID, id)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationDays,
		&i.Price,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionTransactionByMerchantRef = `-- name: GetSubscriptionTransactionByMerchantRef :one
SELECT st.id, st.reference, st.merchant_ref, st.store_id, st.plan_id, st.amount, st.payment_method, st.payment_name, st.status, st.pay_code, st.qr_url, st.checkout_url, st.instructions_json, st.expires_at, st.paid_at, st.created_at, st.updated_at, sp.name as plan_name, sp.duration_days, s.store_name
FROM subscription_transactions st
JOIN subscription_plans sp ON st.plan_id = sp.id
JOIN stores s ON st.store_id = s.id
WHERE st.merchant_ref = $1
`

type GetSubscriptionTransactionByMerchantRefRow struct {
	ID               int32              `json:"id"`
	Reference        string             `json:"reference"`
	MerchantRef      string             `json:"merchant_ref"`
	StoreID          pgtype.UUID        `json:"store_id"`
	PlanID           int32              `json:"plan_id"`
	Amount           int64              `json:"amount"`
	PaymentMethod    string             `json:"payment_method"`
	PaymentName      string             `json:"payment_name"`
	Status           string             `json:"status"`
	PayCode          string             `json:"pay_code"`
	QrUrl            string             `json:"qr_url"`
	CheckoutUrl      string             `json:"checkout_url"`
	InstructionsJson string             `json:"instructions_json"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	PlanName         string             `json:"plan_name"`
	DurationDays     int32              `json:"duration_days"`
	StoreName        string             `json:"store_name"`
}

func (q *Queries) GetSubscriptionTransactionByMerchantRef(ctx context.Context, merchantRef string) (GetSubscriptionTransactionByMerchantRefRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionTransactionByMerchantRef, merchantRef)
	var i GetSubscriptionTransactionByMerchantRefRow
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.MerchantRef,
		&i.StoreID,
		&i.PlanID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentName,
		&i.Status,
		&i.PayCode,
		&i.QrUrl,
		&i.CheckoutUrl,
		&i.InstructionsJson,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanName,
		&i.DurationDays,
		&i.StoreName,
	)
	return i, err
}

const getSubscriptionTransactionByReference = `-- name: GetSubscriptionTransactionByReference :one
SELECT st.id, st.reference, st.merchant_ref, st.store_id, st.plan_id, st.amount, st.payment_method, st.payment_name, st.status, st.pay_code, st.qr_url, st.checkout_url, st.instructions_json, st.expires_at, st.paid_at, st.created_at, st.updated_at, sp.name as plan_name, sp.duration_days, s.store_name
FROM subscription_transactions st
JOIN subscription_plans sp ON st.plan_id = sp.id
JOIN stores s ON st.store_id = s.id
WHERE st.reference = $1
`

type GetSubscriptionTransactionByReferenceRow struct {
	ID               int32              `json:"id"`
	Reference        string             `json:"reference"`
	MerchantRef      string             `json:"merchant_ref"`
	StoreID          pgtype.UUID        `json:"store_id"`
	PlanID           int32              `json:"plan_id"`
	Amount           int64              `json:"amount"`
	PaymentMethod    string             `json:"payment_method"`
	PaymentName      string             `json:"payment_name"`
	Status           string             `json:"status"`
	PayCode          string             `json:"pay_code"`
	QrUrl            string             `json:"qr_url"`
	CheckoutUrl      string             `json:"checkout_url"`
	InstructionsJson string             `json:"instructions_json"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	PlanName         string             `json:"plan_name"`
	DurationDays     int32              `json:"duration_days"`
	StoreName        string             `json:"store_name"`
}

func (q *Queries) GetSubscriptionTransactionByReference(ctx context.Context, reference string) (GetSubscriptionTransactionByReferenceRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionTransactionByReference, reference)
	var i GetSubscriptionTransactionByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.MerchantRef,
		&i.StoreID,
		&i.PlanID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentName,
		&i.Status,
		&i.PayCode,
		&i.QrUrl,
		&i.CheckoutUrl,
		&i.InstructionsJson,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanName,
		&i.DurationDays,
		&i.StoreName,
	)
	return i, err
}

const listActiveSubscriptionPlans = `-- name: ListActiveSubscriptionPlans :many
SELECT id, name, duration_days, price, description, is_active, created_at, updated_at FROM subscription_plans WHERE is_active = TRUE ORDER BY price ASC
`

func (q *Queries) ListActiveSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, listActiveSubscriptionPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionPlan
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationDays,
			&i.Price,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSubscriptionPlans = `-- name: ListAllSubscriptionPlans :many
SELECT id, name, duration_days, price, description, is_active, created_at, updated_at FROM subscription_plans ORDER BY id DESC
`

func (q *Queries) ListAllSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, listAllSubscriptionPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionPlan
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationDays,
			&i.Price,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionTransactions = `-- name: ListSubscriptionTransactions :many
SELECT st.id, st.reference, st.merchant_ref, st.store_id, st.plan_id, st.amount, st.payment_method, st.payment_name, st.status, st.pay_code, st.qr_url, st.checkout_url, st.instructions_json, st.expires_at, st.paid_at, st.created_at, st.updated_at, sp.name as plan_name, s.store_name
FROM subscription_transactions st
JOIN subscription_plans sp ON st.plan_id = sp.id
JOIN stores s ON st.store_id = s.id
ORDER BY st.id DESC
`

type ListSubscriptionTransactionsRow struct {
	ID               int32              `json:"id"`
	Reference        string             `json:"reference"`
	MerchantRef      string             `json:"merchant_ref"`
	StoreID          pgtype.UUID        `json:"store_id"`
	PlanID           int32              `json:"plan_id"`
	Amount           int64              `json:"amount"`
	PaymentMethod    string             `json:"payment_method"`
	PaymentName      string             `json:"payment_name"`
	Status           string             `json:"status"`
	PayCode          string             `json:"pay_code"`
	QrUrl            string             `json:"qr_url"`
	CheckoutUrl      string             `json:"checkout_url"`
	InstructionsJson string             `json:"instructions_json"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	PlanName         string             `json:"plan_name"`
	StoreName        string             `json:"store_name"`
}

func (q *Queries) ListSubscriptionTransactions(ctx context.Context) ([]ListSubscriptionTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionTransactionsRow
	for rows.Next() {
		var i ListSubscriptionTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.MerchantRef,
			&i.StoreID,
			&i.PlanID,
			&i.Amount,
			&i.PaymentMethod,
			&i.PaymentName,
			&i.Status,
			&i.PayCode,
			&i.QrUrl,
			&i.CheckoutUrl,
			&i.InstructionsJson,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanName,
			&i.StoreName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoreProExpiry = `-- name: UpdateStoreProExpiry :one
UPDATE stores
SET pro_expires_at = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, owner_id, store_code, store_name, address, phone, is_active, created_at, updated_at, logo_url, pro_expires_at
`

type UpdateStoreProExpiryParams struct {
	ProExpiresAt pgtype.Timestamptz `json:"pro_expires_at"`
	ID           pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateStoreProExpiry(ctx context.Context, arg UpdateStoreProExpiryParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreProExpiry, arg.ProExpiresAt, arg.ID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StoreCode,
		&i.StoreName,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
		&i.ProExpiresAt,
	)
	return i, err
}

const updateSubscriptionPlan = `-- name: UpdateSubscriptionPlan :one
UPDATE subscription_plans
SET name = $1, duration_days = $2, price = $3, description = $4, is_active = $5, updated_at = NOW()
WHERE id = $6
RETURNING id, name, duration_days, price, description, is_active, created_at, updated_at
`

type UpdateSubscriptionPlanParams struct {
	Name         string `json:"name"`
	DurationDays int32  `json:"duration_days"`
	Price        int64  `json:"price"`
	Description  string `json:"description"`
	IsActive     bool   `json:"is_active"`
	ID           int32  `json:"id"`
}

func (q *Queries) UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionPlan,
		arg.Name,
		arg.DurationDays,
		arg.Price,
		arg.Description,
		arg.IsActive,
		arg.ID,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationDays,
		&i.Price,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionTransactionStatus = `-- name: UpdateSubscriptionTransactionStatus :one
UPDATE subscription_transactions
SET status = $1, paid_at = $2, updated_at = NOW()
WHERE reference = $3
RETURNING id, reference, merchant_ref, store_id, plan_id, amount, payment_method, payment_name, status, pay_code, qr_url, checkout_url, instructions_json, expires_at, paid_at, created_at, updated_at
`

type UpdateSubscriptionTransactionStatusParams struct {
	Status    string             `json:"status"`
	PaidAt    pgtype.Timestamptz `json:"paid_at"`
	Reference string             `json:"reference"`
}

func (q *Queries) UpdateSubscriptionTransactionStatus(ctx context.Context, arg UpdateSubscriptionTransactionStatusParams) (SubscriptionTransaction, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionTransactionStatus, arg.Status, arg.PaidAt, arg.Reference)
	var i SubscriptionTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.MerchantRef,
		&i.StoreID,
		&i.PlanID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentName,
		&i.Status,
		&i.PayCode,
		&i.QrUrl,
		&i.CheckoutUrl,
		&i.InstructionsJson,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
