// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: transaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  store_id, cashier_id, invoice_number, total_amount, paid_amount, change_amount, payment_method, transaction_time, sync_status, device_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, store_id, cashier_id, invoice_number, total_amount, paid_amount, change_amount, payment_method, transaction_time, sync_status, device_id, is_active, created_at, updated_at
`

type CreateTransactionParams struct {
	StoreID         pgtype.UUID      `json:"store_id"`
	CashierID       pgtype.UUID      `json:"cashier_id"`
	InvoiceNumber   string           `json:"invoice_number"`
	TotalAmount     pgtype.Numeric   `json:"total_amount"`
	PaidAmount      pgtype.Numeric   `json:"paid_amount"`
	ChangeAmount    pgtype.Numeric   `json:"change_amount"`
	PaymentMethod   string           `json:"payment_method"`
	TransactionTime pgtype.Timestamp `json:"transaction_time"`
	SyncStatus      string           `json:"sync_status"`
	DeviceID        pgtype.Text      `json:"device_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.StoreID,
		arg.CashierID,
		arg.InvoiceNumber,
		arg.TotalAmount,
		arg.PaidAmount,
		arg.ChangeAmount,
		arg.PaymentMethod,
		arg.TransactionTime,
		arg.SyncStatus,
		arg.DeviceID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CashierID,
		&i.InvoiceNumber,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.ChangeAmount,
		&i.PaymentMethod,
		&i.TransactionTime,
		&i.SyncStatus,
		&i.DeviceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransactionItem = `-- name: CreateTransactionItem :one
INSERT INTO transaction_items (
  transaction_id, store_product_id, master_product_id, product_name, barcode, quantity, buy_price, sell_price, subtotal
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, transaction_id, store_product_id, master_product_id, product_name, barcode, quantity, buy_price, sell_price, subtotal, is_active, created_at, updated_at
`

type CreateTransactionItemParams struct {
	TransactionID   pgtype.UUID    `json:"transaction_id"`
	StoreProductID  pgtype.UUID    `json:"store_product_id"`
	MasterProductID pgtype.UUID    `json:"master_product_id"`
	ProductName     string         `json:"product_name"`
	Barcode         string         `json:"barcode"`
	Quantity        int32          `json:"quantity"`
	BuyPrice        pgtype.Numeric `json:"buy_price"`
	SellPrice       pgtype.Numeric `json:"sell_price"`
	Subtotal        pgtype.Numeric `json:"subtotal"`
}

func (q *Queries) CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) (TransactionItem, error) {
	row := q.db.QueryRow(ctx, createTransactionItem,
		arg.TransactionID,
		arg.StoreProductID,
		arg.MasterProductID,
		arg.ProductName,
		arg.Barcode,
		arg.Quantity,
		arg.BuyPrice,
		arg.SellPrice,
		arg.Subtotal,
	)
	var i TransactionItem
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.StoreProductID,
		&i.MasterProductID,
		&i.ProductName,
		&i.Barcode,
		&i.Quantity,
		&i.BuyPrice,
		&i.SellPrice,
		&i.Subtotal,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
