// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO stock_movements (
  store_id, store_product_id, movement_type, quantity, reference_type, reference_id
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, store_id, store_product_id, movement_type, quantity, reference_type, reference_id, is_active, created_at, updated_at
`

type CreateStockMovementParams struct {
	StoreID        pgtype.UUID `json:"store_id"`
	StoreProductID pgtype.UUID `json:"store_product_id"`
	MovementType   string      `json:"movement_type"`
	Quantity       int32       `json:"quantity"`
	ReferenceType  pgtype.Text `json:"reference_type"`
	ReferenceID    pgtype.UUID `json:"reference_id"`
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, createStockMovement,
		arg.StoreID,
		arg.StoreProductID,
		arg.MovementType,
		arg.Quantity,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.StoreProductID,
		&i.MovementType,
		&i.Quantity,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  store_id, cashier_id, invoice_number, total_amount, paid_amount, change_amount, payment_method, transaction_time, sync_status, device_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, store_id, cashier_id, invoice_number, total_amount, paid_amount, change_amount, payment_method, transaction_time, sync_status, device_id, is_active, created_at, updated_at, is_reported
`

type CreateTransactionParams struct {
	StoreID         pgtype.UUID      `json:"store_id"`
	CashierID       pgtype.UUID      `json:"cashier_id"`
	InvoiceNumber   string           `json:"invoice_number"`
	TotalAmount     int64            `json:"total_amount"`
	PaidAmount      int64            `json:"paid_amount"`
	ChangeAmount    int64            `json:"change_amount"`
	PaymentMethod   string           `json:"payment_method"`
	TransactionTime pgtype.Timestamp `json:"transaction_time"`
	SyncStatus      string           `json:"sync_status"`
	DeviceID        pgtype.Text      `json:"device_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.StoreID,
		arg.CashierID,
		arg.InvoiceNumber,
		arg.TotalAmount,
		arg.PaidAmount,
		arg.ChangeAmount,
		arg.PaymentMethod,
		arg.TransactionTime,
		arg.SyncStatus,
		arg.DeviceID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CashierID,
		&i.InvoiceNumber,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.ChangeAmount,
		&i.PaymentMethod,
		&i.TransactionTime,
		&i.SyncStatus,
		&i.DeviceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsReported,
	)
	return i, err
}

const createTransactionItem = `-- name: CreateTransactionItem :one
INSERT INTO transaction_items (
  transaction_id, store_product_id, master_product_id, product_name, barcode, quantity, buy_price, sell_price, subtotal
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, transaction_id, store_product_id, master_product_id, product_name, barcode, quantity, buy_price, sell_price, subtotal, is_active, created_at, updated_at
`

type CreateTransactionItemParams struct {
	TransactionID   pgtype.UUID `json:"transaction_id"`
	StoreProductID  pgtype.UUID `json:"store_product_id"`
	MasterProductID pgtype.UUID `json:"master_product_id"`
	ProductName     string      `json:"product_name"`
	Barcode         string      `json:"barcode"`
	Quantity        int32       `json:"quantity"`
	BuyPrice        int64       `json:"buy_price"`
	SellPrice       int64       `json:"sell_price"`
	Subtotal        int64       `json:"subtotal"`
}

func (q *Queries) CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) (TransactionItem, error) {
	row := q.db.QueryRow(ctx, createTransactionItem,
		arg.TransactionID,
		arg.StoreProductID,
		arg.MasterProductID,
		arg.ProductName,
		arg.Barcode,
		arg.Quantity,
		arg.BuyPrice,
		arg.SellPrice,
		arg.Subtotal,
	)
	var i TransactionItem
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.StoreProductID,
		&i.MasterProductID,
		&i.ProductName,
		&i.Barcode,
		&i.Quantity,
		&i.BuyPrice,
		&i.SellPrice,
		&i.Subtotal,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllStoreTransactions = `-- name: GetAllStoreTransactions :many
SELECT id, store_id, cashier_id, invoice_number, total_amount, paid_amount, change_amount, payment_method, transaction_time, sync_status, device_id, is_active, created_at, updated_at, is_reported FROM transactions
WHERE store_id = $1
ORDER BY transaction_time DESC
`

func (q *Queries) GetAllStoreTransactions(ctx context.Context, storeID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getAllStoreTransactions, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CashierID,
			&i.InvoiceNumber,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.ChangeAmount,
			&i.PaymentMethod,
			&i.TransactionTime,
			&i.SyncStatus,
			&i.DeviceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsReported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllStoreTransactionsByCashier = `-- name: GetAllStoreTransactionsByCashier :many
SELECT id, store_id, cashier_id, invoice_number, total_amount, paid_amount, change_amount, payment_method, transaction_time, sync_status, device_id, is_active, created_at, updated_at, is_reported FROM transactions
WHERE store_id = $1 AND cashier_id = $2
ORDER BY transaction_time DESC
`

type GetAllStoreTransactionsByCashierParams struct {
	StoreID   pgtype.UUID `json:"store_id"`
	CashierID pgtype.UUID `json:"cashier_id"`
}

func (q *Queries) GetAllStoreTransactionsByCashier(ctx context.Context, arg GetAllStoreTransactionsByCashierParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getAllStoreTransactionsByCashier, arg.StoreID, arg.CashierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CashierID,
			&i.InvoiceNumber,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.ChangeAmount,
			&i.PaymentMethod,
			&i.TransactionTime,
			&i.SyncStatus,
			&i.DeviceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsReported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentStoreTransactions = `-- name: GetRecentStoreTransactions :many
SELECT id, store_id, cashier_id, invoice_number, total_amount, paid_amount, change_amount, payment_method, transaction_time, sync_status, device_id, is_active, created_at, updated_at, is_reported FROM transactions
WHERE store_id = $1
ORDER BY transaction_time DESC
LIMIT 5
`

func (q *Queries) GetRecentStoreTransactions(ctx context.Context, storeID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getRecentStoreTransactions, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CashierID,
			&i.InvoiceNumber,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.ChangeAmount,
			&i.PaymentMethod,
			&i.TransactionTime,
			&i.SyncStatus,
			&i.DeviceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsReported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentStoreTransactionsByCashier = `-- name: GetRecentStoreTransactionsByCashier :many
SELECT id, store_id, cashier_id, invoice_number, total_amount, paid_amount, change_amount, payment_method, transaction_time, sync_status, device_id, is_active, created_at, updated_at, is_reported FROM transactions
WHERE store_id = $1 AND cashier_id = $2
ORDER BY transaction_time DESC
LIMIT 5
`

type GetRecentStoreTransactionsByCashierParams struct {
	StoreID   pgtype.UUID `json:"store_id"`
	CashierID pgtype.UUID `json:"cashier_id"`
}

func (q *Queries) GetRecentStoreTransactionsByCashier(ctx context.Context, arg GetRecentStoreTransactionsByCashierParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getRecentStoreTransactionsByCashier, arg.StoreID, arg.CashierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CashierID,
			&i.InvoiceNumber,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.ChangeAmount,
			&i.PaymentMethod,
			&i.TransactionTime,
			&i.SyncStatus,
			&i.DeviceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsReported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreDashboardStats = `-- name: GetStoreDashboardStats :one
SELECT
    COALESCE(SUM(CASE WHEN DATE(transaction_time) = CURRENT_DATE THEN total_amount ELSE 0 END), 0)::BIGINT AS total_revenue,
    COUNT(CASE WHEN DATE(transaction_time) = CURRENT_DATE THEN id ELSE NULL END)::INT AS total_transactions,
    (SELECT COUNT(store_products.id)::INT FROM store_products WHERE store_products.store_id = $1 AND store_products.is_active = true) AS total_products,
    COALESCE(
        (SELECT SUM(ti.subtotal - (ti.buy_price * ti.quantity))
         FROM transaction_items ti
         JOIN transactions t ON ti.transaction_id = t.id
         WHERE t.store_id = $1 AND DATE(t.transaction_time) = CURRENT_DATE), 0
    )::BIGINT AS net_profit
FROM transactions
WHERE transactions.store_id = $1
`

type GetStoreDashboardStatsRow struct {
	TotalRevenue      int64 `json:"total_revenue"`
	TotalTransactions int32 `json:"total_transactions"`
	TotalProducts     int32 `json:"total_products"`
	NetProfit         int64 `json:"net_profit"`
}

func (q *Queries) GetStoreDashboardStats(ctx context.Context, storeID pgtype.UUID) (GetStoreDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getStoreDashboardStats, storeID)
	var i GetStoreDashboardStatsRow
	err := row.Scan(
		&i.TotalRevenue,
		&i.TotalTransactions,
		&i.TotalProducts,
		&i.NetProfit,
	)
	return i, err
}

const getStoreDashboardStatsByCashier = `-- name: GetStoreDashboardStatsByCashier :one
SELECT
    COALESCE(SUM(CASE WHEN DATE(transaction_time) = CURRENT_DATE THEN total_amount ELSE 0 END), 0)::BIGINT AS total_revenue,
    COUNT(CASE WHEN DATE(transaction_time) = CURRENT_DATE THEN id ELSE NULL END)::INT AS total_transactions,
    (SELECT COUNT(store_products.id)::INT FROM store_products WHERE store_products.store_id = $1 AND store_products.is_active = true) AS total_products,
    COALESCE(
        (SELECT SUM(ti.subtotal - (ti.buy_price * ti.quantity))
         FROM transaction_items ti
         JOIN transactions t ON ti.transaction_id = t.id
         WHERE t.store_id = $1 AND t.cashier_id = $2 AND DATE(t.transaction_time) = CURRENT_DATE), 0
    )::BIGINT AS net_profit
FROM transactions
WHERE transactions.store_id = $1 AND transactions.cashier_id = $2
`

type GetStoreDashboardStatsByCashierParams struct {
	StoreID   pgtype.UUID `json:"store_id"`
	CashierID pgtype.UUID `json:"cashier_id"`
}

type GetStoreDashboardStatsByCashierRow struct {
	TotalRevenue      int64 `json:"total_revenue"`
	TotalTransactions int32 `json:"total_transactions"`
	TotalProducts     int32 `json:"total_products"`
	NetProfit         int64 `json:"net_profit"`
}

func (q *Queries) GetStoreDashboardStatsByCashier(ctx context.Context, arg GetStoreDashboardStatsByCashierParams) (GetStoreDashboardStatsByCashierRow, error) {
	row := q.db.QueryRow(ctx, getStoreDashboardStatsByCashier, arg.StoreID, arg.CashierID)
	var i GetStoreDashboardStatsByCashierRow
	err := row.Scan(
		&i.TotalRevenue,
		&i.TotalTransactions,
		&i.TotalProducts,
		&i.NetProfit,
	)
	return i, err
}

const getTransactionItemsByTransactionId = `-- name: GetTransactionItemsByTransactionId :many
SELECT id, transaction_id, store_product_id, master_product_id, product_name, barcode, quantity, buy_price, sell_price, subtotal, is_active, created_at, updated_at FROM transaction_items
WHERE transaction_id = $1
`

func (q *Queries) GetTransactionItemsByTransactionId(ctx context.Context, transactionID pgtype.UUID) ([]TransactionItem, error) {
	rows, err := q.db.Query(ctx, getTransactionItemsByTransactionId, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionItem
	for rows.Next() {
		var i TransactionItem
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.StoreProductID,
			&i.MasterProductID,
			&i.ProductName,
			&i.Barcode,
			&i.Quantity,
			&i.BuyPrice,
			&i.SellPrice,
			&i.Subtotal,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreportedTransactionsByCashier = `-- name: GetUnreportedTransactionsByCashier :many
SELECT id, store_id, cashier_id, invoice_number, total_amount, paid_amount, change_amount, payment_method, transaction_time, sync_status, device_id, is_active, created_at, updated_at, is_reported FROM transactions
WHERE store_id = $1 AND cashier_id = $2 AND is_reported = FALSE
ORDER BY transaction_time ASC
`

type GetUnreportedTransactionsByCashierParams struct {
	StoreID   pgtype.UUID `json:"store_id"`
	CashierID pgtype.UUID `json:"cashier_id"`
}

func (q *Queries) GetUnreportedTransactionsByCashier(ctx context.Context, arg GetUnreportedTransactionsByCashierParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getUnreportedTransactionsByCashier, arg.StoreID, arg.CashierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CashierID,
			&i.InvoiceNumber,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.ChangeAmount,
			&i.PaymentMethod,
			&i.TransactionTime,
			&i.SyncStatus,
			&i.DeviceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsReported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransactionsAsReported = `-- name: MarkTransactionsAsReported :exec
UPDATE transactions
SET is_reported = TRUE
WHERE store_id = $1 AND cashier_id = $2 AND is_reported = FALSE
`

type MarkTransactionsAsReportedParams struct {
	StoreID   pgtype.UUID `json:"store_id"`
	CashierID pgtype.UUID `json:"cashier_id"`
}

func (q *Queries) MarkTransactionsAsReported(ctx context.Context, arg MarkTransactionsAsReportedParams) error {
	_, err := q.db.Exec(ctx, markTransactionsAsReported, arg.StoreID, arg.CashierID)
	return err
}

const updateTransactionReportStatus = `-- name: UpdateTransactionReportStatus :exec
UPDATE transactions
SET is_reported = $1
WHERE id = $2
`

type UpdateTransactionReportStatusParams struct {
	IsReported bool        `json:"is_reported"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTransactionReportStatus(ctx context.Context, arg UpdateTransactionReportStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransactionReportStatus, arg.IsReported, arg.ID)
	return err
}
