// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  full_name, email, phone, password_hash, role, store_id
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, full_name, email, phone, password_hash, role, store_id, is_active, created_at, updated_at, photo_url
`

type CreateUserParams struct {
	FullName     string      `json:"full_name"`
	Email        pgtype.Text `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	StoreID      pgtype.UUID `json:"store_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
		arg.StoreID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.StoreID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhotoUrl,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, full_name, email, phone, password_hash, role, store_id, is_active, created_at, updated_at, photo_url FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.StoreID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhotoUrl,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, phone, password_hash, role, store_id, is_active, created_at, updated_at, photo_url FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.StoreID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhotoUrl,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, email, phone, password_hash, role, store_id, is_active, created_at, updated_at, photo_url FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.Role,
			&i.StoreID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByStore = `-- name: ListUsersByStore :many
SELECT id, full_name, email, phone, password_hash, role, store_id, is_active, created_at, updated_at, photo_url FROM users
WHERE store_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListUsersByStore(ctx context.Context, storeID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.Role,
			&i.StoreID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
  full_name = COALESCE($2, full_name),
  photo_url = COALESCE($3, photo_url),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, full_name, email, phone, password_hash, role, store_id, is_active, created_at, updated_at, photo_url
`

type UpdateUserProfileParams struct {
	ID       pgtype.UUID `json:"id"`
	FullName pgtype.Text `json:"full_name"`
	PhotoUrl pgtype.Text `json:"photo_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.FullName, arg.PhotoUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.StoreID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhotoUrl,
	)
	return i, err
}

const updateUserStoreID = `-- name: UpdateUserStoreID :exec
UPDATE users SET store_id = $2 WHERE id = $1
`

type UpdateUserStoreIDParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

func (q *Queries) UpdateUserStoreID(ctx context.Context, arg UpdateUserStoreIDParams) error {
	_, err := q.db.Exec(ctx, updateUserStoreID, arg.ID, arg.StoreID)
	return err
}
